# 01. Numpy

In [8]:
# 212-01 넘파이 임포트
import numpy as np

In [9]:
# 212-02 넘파이 배열 형태
a1 = np.array([1, 2, 3])
print(a1)
print('array1 type : ', type(a1))
print('array1 shape : ', a1.shape)  # 1차원 배열에 3개의 데이터

a2 = np.array([[1, 2, 3], [4, 5, 6]])
print(a2)
print('array2 type : ', type(a2))
print('array2 shape : ', a2.shape)  # 2차원 배열, 2개의 행과 3개의 칼럼 데이터 

a3 = np.array([[1, 2, 3]])
print(a3)
print('array3 type : ', type(a3))
print('array3 shape : ', a3.shape)  # 2차원 배열, 1개의 행과 3개의 칼럼

[1 2 3]
array1 type :  <class 'numpy.ndarray'>
array1 shape :  (3,)
[[1 2 3]
 [4 5 6]]
array2 type :  <class 'numpy.ndarray'>
array2 shape :  (2, 3)
[[1 2 3]]
array3 type :  <class 'numpy.ndarray'>
array3 shape :  (1, 3)


In [10]:
# 212-03 넘파이 배열 차원
print('array 1 dim :', a1.ndim)  # 1차원 배열
print('array 2 dim :', a2.ndim)  # 2차원 배열
print('array 3 dim :', a3.ndim)  # 2차원 배열

array 1 dim : 1
array 2 dim : 2
array 3 dim : 2


In [11]:
# 212-04 넘파이 arange 함수 기본
a = np.arange(20)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [12]:
# 212-05 넘파이 arange 함수 응용
a = np.arange(1, 20 ,3)
print(a)

[ 1  4  7 10 13 16 19]


In [13]:
# 213-01 넘파이 zeros, ones 함수
zero_a = np.zeros((2, 5))
one_a = np.ones((3, 4))
print(zero_a)
print(one_a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
# 213-02 넘파이 zeros_like함수
zero_b = np.zeros_like(one_a)
print(zero_b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
# 213-03 넘파이 ones_like함수
one_b = np.ones_like(zero_a)
print(one_b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
# 213-04 넘파이 full, random 함수
full_a = np.full((4, 3), 9)
random_a = np.random.random((3, 4))

print(full_a)
print(random_a)

[[9 9 9]
 [9 9 9]
 [9 9 9]
 [9 9 9]]
[[0.73281524 0.7104828  0.3063371  0.68496705]
 [0.94110787 0.60642247 0.92000172 0.71718665]
 [0.54135405 0.34987047 0.97570155 0.8645934 ]]


In [17]:
# 213-05 넘파이 eye함수
eye_a = np.eye(4)
print(eye_a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [19]:
# 214-01 넘파이 reshape함수 기본
array1 = np.arange(12)
print('array1 : \n', array1)

array2 = array1.reshape(3,4)
print('array2 : \n', array2)

array3 = array1.reshape(3,4,order='F')
print('array3 : \n', array3)

array1 : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
array2 : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
array3 : 
 [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [20]:
# 214-02 넘파이 reshape 함수 응용
array1 = np.arange(10)
array2 = array1.reshape(-1, 5)

print(array2)
print('array2 dim : ', array2.ndim)
print('array2 shape : ', array2.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
array2 dim :  2
array2 shape :  (2, 5)


In [21]:
# 214-03 넘파이 reshape 함수 다차원 변형
array1 = np.arange(12)
array2 = array1.reshape(2, 3, 2, order = 'F')

print(array2)
print('array2 dim : ', array2.ndim)
print('array2 shape : ', array2.shape)

[[[ 0  6]
  [ 2  8]
  [ 4 10]]

 [[ 1  7]
  [ 3  9]
  [ 5 11]]]
array2 dim :  3
array2 shape :  (2, 3, 2)


In [22]:
# 214-04 넘파이 flatten 함수 1차원 변형
array3 = array2.flatten()
print(array3)

[ 0  6  2  8  4 10  1  7  3  9  5 11]


In [23]:
# 215-01 넘파이 1차원 배열 단일값 추출
array1 = np.arange(1, 10)
print('array1 : ', array1)

value1 = array1[2]
value2 = array1[-2]

print(value1)
print(value2)

array1 :  [1 2 3 4 5 6 7 8 9]
3
8


In [25]:
# 215-02 넘파이 다차원 배열 단일값 추출
array1 = np.arange(1, 10)
array2 = array1.reshape(3, 3)
print('array2 : \n', array2)

value1 = array2[0, 0]
value2 = array2[-1, -1]
value3 = array2[-1, -2]

print(value1)
print(value2)
print(value3)

array2 : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
1
9
8


In [26]:
# 215-03 넘파이 1차원 배열 슬라이싱 추출
array1 = np.arange(1, 10)
array2 = array1[0:3]
array3 = array1[:3]
array4 = array1[3:]

print(type(array2))
print(array2)
print(array3)
print(array4)

<class 'numpy.ndarray'>
[1 2 3]
[1 2 3]
[4 5 6 7 8 9]


In [29]:
# 215-04 넘파이 다차원 배열 슬라이싱 추출
array1 = np.arange(1, 10)
array2 = array1.reshape(3, 3)
print('array2 : \n', array2)

print('array2[0:2, 0:2]\n', array2[0:2, 0:2])
print('array2[1:3, 0:3]\n', array2[1:3, 0:3])
print('array2[:2, 1:]\n', array2[:2, 1:])
print('array2[:2, 0]\n', array2[0:2, 0])

array2 : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2[0:2, 0:2]
 [[1 2]
 [4 5]]
array2[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]
array2[:2, 1:]
 [[2 3]
 [5 6]]
array2[:2, 0]
 [1 4]


In [30]:
# 216-01 넘파이 행렬 내적 계산
array1 = np.array([[1,2,3],
                   [4,5,6]])
array2 = np.array([[7,8],
                   [9,10],
                   [11,12]])
dot_array = np.dot(array1, array2)
print(dot_array)

[[ 58  64]
 [139 154]]


In [32]:
# 216-02 넘파이 전치 행렬 계산
array1 = np.array([[1,2,3],
                   [4,5,6]])
transpose_array = np.transpose(array1)
print(transpose_array)

[[1 4]
 [2 5]
 [3 6]]


In [33]:
# 217-01 배열 데이터 개수 계산
x = np.array([18, 5, 10, 23, 19, -8, 10, 0, 0, 5, 2, 15, 8,
              2, 5, 4, 15, -1, 4, -7])
len(x)

20

In [34]:
# 217-02 평균, 분산, 표준편차 계산
print(np.mean(x))  # 평균
print(np.var(x))  # 분산
print(np.std(x))  # 표준편차

6.45
66.2475
8.13925672282181


In [35]:
# 217-03 최댓값, 최솟값, 중앙값 계산
print(np.max(x))  # 최댓값
print(np.min(x))  # 최소값
print(np.median(x))  # 중앙값

23
-8
5.0


In [36]:
# 217-04 사분위수 계산
print(np.percentile(x, 25))
print(np.percentile(x, 50))
print(np.percentile(x, 75))

1.5
5.0
11.25


# 02. Pandas

In [1]:
# 222-01 판다스 임포트
import pandas as pd

In [38]:
# 222-02 시리즈
s = pd.Series([1, 3, 5, 6, 8])
print(s)
print(s.index)
print(s.values)

0    1
1    3
2    5
3    6
4    8
dtype: int64
RangeIndex(start=0, stop=5, step=1)
[1 3 5 6 8]


In [39]:
# 222-03 데이터프레임
v = [[1, 2, 3,], [4, 5, 6], [7, 8, 9]]
i = ['첫째행', '둘째행', '셋째행']
c = ['컬럼1', '컬럼2', '컬럼3']

df = pd.DataFrame(v, index=i, columns =c)
print(df)

     컬럼1  컬럼2  컬럼3
첫째행    1    2    3
둘째행    4    5    6
셋째행    7    8    9


In [40]:
# 223-01 리스트로 생성하기
d = [
    ['100', '강백호', 9.7],
    ['101', '송태섭', 8.9],
    ['102', '서태웅', 9.3],
    ['103', '채치수', 6.1],
    ]
df = pd.DataFrame(d, columns=['번호', '이름', '점수'])
print(df)

    번호   이름   점수
0  100  강백호  9.7
1  101  송태섭  8.9
2  102  서태웅  9.3
3  103  채치수  6.1


In [42]:
# 223-02 딕셔너리로 생성하기
d = {
    '번호' : ['100', '101', '102', '103'],
    '이름' : ['강백호', '송태섭', '서태웅', '채치수'],
    '점수' : [9.7, 8.9, 9.3, 6.1],
    }
df = pd.DataFrame(d)
print(df)

    번호   이름   점수
0  100  강백호  9.7
1  101  송태섭  8.9
2  102  서태웅  9.3
3  103  채치수  6.1


In [51]:
# 223-03 csv파일로 생성하기
iris_df = pd.read_csv('data/datasets/part2/iris.csv')
print('iris 변수 type : ', type(iris_df))
print(iris_df)

iris 변수 type :  <class 'pandas.core.frame.DataFrame'>
     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]


In [52]:
# 224-01 데이터프레임 head 함수
print('DataFrame 크기 : ', iris_df.shape)
print(iris_df.head(5))

DataFrame 크기 :  (150, 5)
   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa


In [53]:
# 224-02 데이터프레임 info 함수
print(iris_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
None


In [54]:
# 224-03 데이터프레임 describe 함수
print(iris_df.describe())

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000


In [57]:
# 224-04 시리즈 head함수
iris_df_sepal_length = iris_df['sepal_length']
print(iris_df_sepal_length.head())

0    5.1
1    4.9
2    4.7
3    4.6
4    5.0
Name: sepal_length, dtype: float64


In [58]:
# 224-05 시리즈 value_counts 함수
value_counts = iris_df_sepal_length.value_counts()
print(value_counts)

sepal_length
5.0    10
5.1     9
6.3     9
5.7     8
6.7     8
5.8     7
5.5     7
6.4     7
4.9     6
5.4     6
6.1     6
6.0     6
5.6     6
4.8     5
6.5     5
6.2     4
7.7     4
6.9     4
4.6     4
5.2     4
5.9     3
4.4     3
7.2     3
6.8     3
6.6     2
4.7     2
7.6     1
7.4     1
7.3     1
7.0     1
7.1     1
5.3     1
4.3     1
4.5     1
7.9     1
Name: count, dtype: int64


In [64]:
# 225-01 신규 칼럼 생성하기 기본
iris_df['Add_0'] = 0
print(iris_df.head())

   sepal_length  sepal_width  petal_length  petal_width species  Add_0
0           5.1          3.5           1.4          0.2  setosa      0
1           4.9          3.0           1.4          0.2  setosa      0
2           4.7          3.2           1.3          0.2  setosa      0
3           4.6          3.1           1.5          0.2  setosa      0
4           5.0          3.6           1.4          0.2  setosa      0


In [65]:
# 225-02 신규 칼럼 생성하기 응용
iris_df['Add_1'] = iris_df['sepal_length'] // 5
print(iris_df.head())

   sepal_length  sepal_width  petal_length  petal_width species  Add_0  Add_1
0           5.1          3.5           1.4          0.2  setosa      0    1.0
1           4.9          3.0           1.4          0.2  setosa      0    0.0
2           4.7          3.2           1.3          0.2  setosa      0    0.0
3           4.6          3.1           1.5          0.2  setosa      0    0.0
4           5.0          3.6           1.4          0.2  setosa      0    1.0


In [66]:
# 225-03 칼럼 데이터 수정하기
iris_df['Add_1'] = iris_df['Add_1'] * 5
print(iris_df.head())

   sepal_length  sepal_width  petal_length  petal_width species  Add_0  Add_1
0           5.1          3.5           1.4          0.2  setosa      0    5.0
1           4.9          3.0           1.4          0.2  setosa      0    0.0
2           4.7          3.2           1.3          0.2  setosa      0    0.0
3           4.6          3.1           1.5          0.2  setosa      0    0.0
4           5.0          3.6           1.4          0.2  setosa      0    5.0


In [67]:
# 225-04 신규 칼럼 value_count 함수
value_counts = iris_df['Add_1'].value_counts()
print(value_counts)

Add_1
5.0    128
0.0     22
Name: count, dtype: int64


In [68]:
# 226-01 칼럼 데이터 삭제하기
iris_drop_df = iris_df.drop('Add_0', axis=1)
print(iris_drop_df.head())

   sepal_length  sepal_width  petal_length  petal_width species  Add_1
0           5.1          3.5           1.4          0.2  setosa    5.0
1           4.9          3.0           1.4          0.2  setosa    0.0
2           4.7          3.2           1.3          0.2  setosa    0.0
3           4.6          3.1           1.5          0.2  setosa    0.0
4           5.0          3.6           1.4          0.2  setosa    5.0


In [70]:
# 226-02 복수 칼럼 데이터 삭제하기
drop_result = iris_df.drop( ['Add_0', 'Add_1'], axis=1, inplace = True)
print('drop_result 반환값 : ', drop_result)
print(iris_df.head())

drop_result 반환값 :  None
   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa


In [71]:
# 226-03 행 데이터 삭제하기
iris_drop_df = iris_df.drop([0, 1, 2], axis=0)
print(iris_drop_df.head())

   sepal_length  sepal_width  petal_length  petal_width species
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa


In [72]:
# 227-01 칼럼명으로 데이터 조회
print('단일 칼럼 데이터 조회 : \n', iris_df['sepal_length'].head())
print('\n복수 칼럼 데이터 조회 : \n', iris_df[['petal_length', 'petal_width']].head())

단일 칼럼 데이터 조회 : 
 0    5.1
1    4.9
2    4.7
3    4.6
4    5.0
Name: sepal_length, dtype: float64

복수 칼럼 데이터 조회 : 
    petal_length  petal_width
0           1.4          0.2
1           1.4          0.2
2           1.3          0.2
3           1.5          0.2
4           1.4          0.2


In [73]:
# 227-02 인덱스 슬라이싱으로 데이터 조회
print(iris_df[0:3])

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa


In [77]:
# 227-03 논리형 인덱싱으로 데이터 조회
print(iris_df[iris_df['sepal_width'] > 3.0].head())

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa


In [ ]:
# 227-04 

# 03. Scikit-learn

In [1]:
# 231-01 사이킷런 임포트
import sklearn
print(sklearn.__version__)

1.2.2


In [2]:
# 234-01 붓꽃 데이터 세트 불러오기
from sklearn.datasets import load_iris

iris = load_iris()
print('붓꽃 데이터세트 타입 : ', type(iris))

keys = iris.keys()
print('붓꽃 데이터세트 키 : ', keys)

붓꽃 데이터세트 타입 :  <class 'sklearn.utils._bunch.Bunch'>
붓꽃 데이터세트 키 :  dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [8]:
# 234-02 붓꽃 데이터세트 키 출력
print('feature_names :')
print(iris.feature_names)
print('\ntarget_names :')
print(iris.target_names)
print('\ndata :')
print(iris.data)
print('\ntarget :')
print(iris.target)

feature_names :
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

target_names :
['setosa' 'versicolor' 'virginica']

data :
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1

In [9]:
# 235-01 붓꽃 데이터 세트 훑어보기
import pandas as pd

iris_df = pd.DataFrame(data = iris.data, columns = iris.feature_names)
iris_df['label'] = iris.target
print(iris_df.head())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   label  
0      0  
1      0  
2      0  
3      0  
4      0  


In [11]:
# 235-02 학습/테스트 데이터 세트 분할
from sklearn.model_selection import train_test_split

iris_data = iris.data
iris_label = iris.target

x_train, x_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size = 0.2, random_state = 11)

print('train dataset')
print('x_train dataset : ', len(x_train))
print('y_train dataset : ', len(y_train))
print('\ntest dataset')
print('x_test dataset : ', len(x_test))
print('y_test dataset : ', len(y_test))      

train dataset
x_train dataset :  120
y_train dataset :  120

test dataset
x_test dataset :  30
y_test dataset :  30


In [13]:
# 235-03 의사결정 트리 머신러닝 학습
from sklearn.tree import DecisionTreeClassifier

dt_clf = DecisionTreeClassifier(random_state = 11)
dt_clf.fit(x_train, y_train)

DecisionTreeClassifier(random_state=11)

In [16]:
# 235-04 의사결정 트리 머신러닝 테스트/평가
from sklearn.metrics import accuracy_score

pred = dt_clf.predict(x_test)
ac_score = accuracy_score(y_test, pred)

print('예측 정확도 : ', ac_score)

예측 정확도 :  0.9333333333333333


In [17]:
# 236-01 레이블 인코딩
from sklearn.preprocessing import LabelEncoder

items = ['TV', '냉장고', '전자레인지', '컴퓨터', 'TV', '냉장고', '컴퓨터', '컴퓨터']

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

print('인코딩 변환값 : ', labels)
print('인코딩 클래스 : ', encoder.classes_)
        

인코딩 변환값 :  [0 1 2 3 0 1 3 3]
인코딩 클래스 :  ['TV' '냉장고' '전자레인지' '컴퓨터']


In [18]:
# 236-02 레이블 디코딩
origins = encoder.inverse_transform([0, 1, 2, 3, 0, 1, 3, 3])

print('디코딩 원본값 : ', origins)

디코딩 원본값 :  ['TV' '냉장고' '전자레인지' '컴퓨터' 'TV' '냉장고' '컴퓨터' '컴퓨터']


In [23]:
# 236-03 원-핫 인코딩
from sklearn.preprocessing import OneHotEncoder
import numpy as np

labels = labels.reshape(-1, 1)  # 숫자형으로 변환된 값을 2차원 데이터로 변환
print(labels)

oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)

print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

[[0]
 [1]
 [2]
 [3]
 [0]
 [1]
 [3]
 [3]]
원-핫 인코딩 데이터
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]
원-핫 인코딩 데이터 차원
(8, 4)


In [24]:
# 236-04 판다스의 원-핫 인코딩
import pandas as pd

item_df = pd.DataFrame({'item' : items})
pd.get_dummies(item_df)

item_TV  item_냉장고  item_전자레인지  item_컴퓨터
0     True     False       False     False
1    False      True       False     False
2    False     False        True     False
3    False     False       False      True
4     True     False       False     False
5    False      True       False     False
6    False     False       False      True
7    False     False       False      True

In [25]:
# 236-05 스케일링 데이터 세트 훑어보기
from sklearn.datasets import load_iris

iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data = iris_data, columns = iris.feature_names)

print('feature 들의 평균 값 : \n', iris_df.mean())
print('feature 들의 분산 값 : \n', iris_df.var())

feature 들의 평균 값 : 
 sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64
feature 들의 분산 값 : 
 sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [26]:
# 236-06 표준화
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()   # 표준화 객체를 생성하고,
scaler.fit(iris_df)         # iris_df 데이터를 학습시키고, 변환된 데이터를 가진다.
iris_scaled = scaler.transform(iris_df) # 변환된 데이터를 호출한다.
iris_df_scaled = pd.DataFrame(data = iris_scaled, columns = iris.feature_names)

print('feature 들의 평균 값 : \n', iris_df_scaled.mean())
print('feature 들의 분산 값 : \n', iris_df_scaled.var())


feature 들의 평균 값 : 
 sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
feature 들의 분산 값 : 
 sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


In [27]:
# 236-07 최대-최소 정규화
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)
iris_df_scaled = pd.DataFrame(data = iris_scaled, columns = iris.feature_names)

print('feature 들의 최소 값 : \n', iris_df_scaled.min())
print('feature 들의 최대 값 : \n', iris_df_scaled.max())

feature 들의 최소 값 : 
 sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64
feature 들의 최대 값 : 
 sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


In [4]:
# 236-08 스케일링 주의사항
from sklearn.preprocessing import MinMaxScaler
import numpy as np

train_array = np.arange(0,11).reshape(-1,1)
test_array = np.arange(0,6).reshape(-1,1)

scaler = MinMaxScaler()
scaler.fit(train_array)
train_scaled = scaler.transform(train_array)

print('원본 train_array 데이터 : ', np.round(train_array.reshape(-1), 2))
print('Scaled train_array 데이터 : ', np.round(train_scaled.reshape(-1), 2))

#scaler.fit(test_array)              # 테스트 데이터로는 학습하지 않는다.
test_scaled = scaler.transform(test_array)

print('원본 train_array 데이터 : ', np.round(test_array.reshape(-1), 2))
print('Scaled train_array 데이터 : ', np.round(test_scaled.reshape(-1), 2))


원본 train_array 데이터 :  [ 0  1  2  3  4  5  6  7  8  9 10]
Scaled train_array 데이터 :  [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
원본 train_array 데이터 :  [0 1 2 3 4 5]
Scaled train_array 데이터 :  [0.  0.1 0.2 0.3 0.4 0.5]
